package cc.aoeiuv020.vpnproxy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.aoeiuv020.vpnproxy.greendao.bean.BlacklistOrAutomaticInterceptionNumberBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLACKLIST_OR_AUTOMATIC_INTERCEPTION_NUMBER_BEAN".
*/
public class BlacklistOrAutomaticInterceptionNumberBeanDao extends AbstractDao<BlacklistOrAutomaticInterceptionNumberBean, Long> {

    public static final String TABLENAME = "BLACKLIST_OR_AUTOMATIC_INTERCEPTION_NUMBER_BEAN";

    /**
     * Properties of entity BlacklistOrAutomaticInterceptionNumberBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AutomaticInterceptionNumber = new Property(1, int.class, "automaticInterceptionNumber", false, "AUTOMATIC_INTERCEPTION_NUMBER");
        public final static Property BlacklistNumber = new Property(2, int.class, "blacklistNumber", false, "BLACKLIST_NUMBER");
    }


    public BlacklistOrAutomaticInterceptionNumberBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BlacklistOrAutomaticInterceptionNumberBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLACKLIST_OR_AUTOMATIC_INTERCEPTION_NUMBER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"AUTOMATIC_INTERCEPTION_NUMBER\" INTEGER NOT NULL ," + // 1: automaticInterceptionNumber
                "\"BLACKLIST_NUMBER\" INTEGER NOT NULL );"); // 2: blacklistNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLACKLIST_OR_AUTOMATIC_INTERCEPTION_NUMBER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlacklistOrAutomaticInterceptionNumberBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getAutomaticInterceptionNumber());
        stmt.bindLong(3, entity.getBlacklistNumber());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlacklistOrAutomaticInterceptionNumberBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getAutomaticInterceptionNumber());
        stmt.bindLong(3, entity.getBlacklistNumber());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BlacklistOrAutomaticInterceptionNumberBean readEntity(Cursor cursor, int offset) {
        BlacklistOrAutomaticInterceptionNumberBean entity = new BlacklistOrAutomaticInterceptionNumberBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // automaticInterceptionNumber
            cursor.getInt(offset + 2) // blacklistNumber
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlacklistOrAutomaticInterceptionNumberBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAutomaticInterceptionNumber(cursor.getInt(offset + 1));
        entity.setBlacklistNumber(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BlacklistOrAutomaticInterceptionNumberBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BlacklistOrAutomaticInterceptionNumberBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlacklistOrAutomaticInterceptionNumberBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
