package cc.aoeiuv020.vpnproxy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.aoeiuv020.vpnproxy.greendao.bean.EducationalConsultingDetals;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EDUCATIONAL_CONSULTING_DETALS".
*/
public class EducationalConsultingDetalsDao extends AbstractDao<EducationalConsultingDetals, Long> {

    public static final String TABLENAME = "EDUCATIONAL_CONSULTING_DETALS";

    /**
     * Properties of entity EducationalConsultingDetals.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ConsultingClassification = new Property(1, String.class, "consultingClassification", false, "CONSULTING_CLASSIFICATION");
        public final static Property ConsultingTitle = new Property(2, String.class, "consultingTitle", false, "CONSULTING_TITLE");
        public final static Property Time = new Property(3, String.class, "time", false, "TIME");
    }


    public EducationalConsultingDetalsDao(DaoConfig config) {
        super(config);
    }
    
    public EducationalConsultingDetalsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EDUCATIONAL_CONSULTING_DETALS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CONSULTING_CLASSIFICATION\" TEXT," + // 1: consultingClassification
                "\"CONSULTING_TITLE\" TEXT," + // 2: consultingTitle
                "\"TIME\" TEXT);"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EDUCATIONAL_CONSULTING_DETALS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EducationalConsultingDetals entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String consultingClassification = entity.getConsultingClassification();
        if (consultingClassification != null) {
            stmt.bindString(2, consultingClassification);
        }
 
        String consultingTitle = entity.getConsultingTitle();
        if (consultingTitle != null) {
            stmt.bindString(3, consultingTitle);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EducationalConsultingDetals entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String consultingClassification = entity.getConsultingClassification();
        if (consultingClassification != null) {
            stmt.bindString(2, consultingClassification);
        }
 
        String consultingTitle = entity.getConsultingTitle();
        if (consultingTitle != null) {
            stmt.bindString(3, consultingTitle);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(4, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EducationalConsultingDetals readEntity(Cursor cursor, int offset) {
        EducationalConsultingDetals entity = new EducationalConsultingDetals( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // consultingClassification
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // consultingTitle
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EducationalConsultingDetals entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setConsultingClassification(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setConsultingTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EducationalConsultingDetals entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EducationalConsultingDetals entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EducationalConsultingDetals entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
