package cc.aoeiuv020.vpnproxy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.aoeiuv020.vpnproxy.greendao.bean.KeywordAddressWebsitesBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEYWORD_ADDRESS_WEBSITES_BEAN".
*/
public class KeywordAddressWebsitesBeanDao extends AbstractDao<KeywordAddressWebsitesBean, Long> {

    public static final String TABLENAME = "KEYWORD_ADDRESS_WEBSITES_BEAN";

    /**
     * Properties of entity KeywordAddressWebsitesBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WebsiteUrl = new Property(1, String.class, "websiteUrl", false, "WEBSITE_URL");
    }


    public KeywordAddressWebsitesBeanDao(DaoConfig config) {
        super(config);
    }
    
    public KeywordAddressWebsitesBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEYWORD_ADDRESS_WEBSITES_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"WEBSITE_URL\" TEXT);"); // 1: websiteUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEYWORD_ADDRESS_WEBSITES_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeywordAddressWebsitesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String websiteUrl = entity.getWebsiteUrl();
        if (websiteUrl != null) {
            stmt.bindString(2, websiteUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeywordAddressWebsitesBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String websiteUrl = entity.getWebsiteUrl();
        if (websiteUrl != null) {
            stmt.bindString(2, websiteUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public KeywordAddressWebsitesBean readEntity(Cursor cursor, int offset) {
        KeywordAddressWebsitesBean entity = new KeywordAddressWebsitesBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // websiteUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeywordAddressWebsitesBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWebsiteUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(KeywordAddressWebsitesBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(KeywordAddressWebsitesBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KeywordAddressWebsitesBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
