package cc.aoeiuv020.vpnproxy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.aoeiuv020.vpnproxy.greendao.bean.VisualProtectionBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VISUAL_PROTECTION_BEAN".
*/
public class VisualProtectionBeanDao extends AbstractDao<VisualProtectionBean, Long> {

    public static final String TABLENAME = "VISUAL_PROTECTION_BEAN";

    /**
     * Properties of entity VisualProtectionBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UseTime = new Property(1, String.class, "useTime", false, "USE_TIME");
        public final static Property LockScreenLength = new Property(2, String.class, "lockScreenLength", false, "LOCK_SCREEN_LENGTH");
        public final static Property IsOpen = new Property(3, boolean.class, "isOpen", false, "IS_OPEN");
    }


    public VisualProtectionBeanDao(DaoConfig config) {
        super(config);
    }
    
    public VisualProtectionBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISUAL_PROTECTION_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USE_TIME\" TEXT," + // 1: useTime
                "\"LOCK_SCREEN_LENGTH\" TEXT," + // 2: lockScreenLength
                "\"IS_OPEN\" INTEGER NOT NULL );"); // 3: isOpen
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISUAL_PROTECTION_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VisualProtectionBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String useTime = entity.getUseTime();
        if (useTime != null) {
            stmt.bindString(2, useTime);
        }
 
        String lockScreenLength = entity.getLockScreenLength();
        if (lockScreenLength != null) {
            stmt.bindString(3, lockScreenLength);
        }
        stmt.bindLong(4, entity.getIsOpen() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VisualProtectionBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String useTime = entity.getUseTime();
        if (useTime != null) {
            stmt.bindString(2, useTime);
        }
 
        String lockScreenLength = entity.getLockScreenLength();
        if (lockScreenLength != null) {
            stmt.bindString(3, lockScreenLength);
        }
        stmt.bindLong(4, entity.getIsOpen() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VisualProtectionBean readEntity(Cursor cursor, int offset) {
        VisualProtectionBean entity = new VisualProtectionBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // useTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // lockScreenLength
            cursor.getShort(offset + 3) != 0 // isOpen
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VisualProtectionBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUseTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLockScreenLength(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsOpen(cursor.getShort(offset + 3) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VisualProtectionBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VisualProtectionBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VisualProtectionBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
