package cc.aoeiuv020.vpnproxy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cc.aoeiuv020.vpnproxy.greendao.bean.VpnProtectStatusBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VPN_PROTECT_STATUS_BEAN".
*/
public class VpnProtectStatusBeanDao extends AbstractDao<VpnProtectStatusBean, Long> {

    public static final String TABLENAME = "VPN_PROTECT_STATUS_BEAN";

    /**
     * Properties of entity VpnProtectStatusBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VpnProtectsSatus = new Property(1, int.class, "vpnProtectsSatus", false, "VPN_PROTECTS_SATUS");
        public final static Property VpnProtectsSatusPormpt = new Property(2, String.class, "vpnProtectsSatusPormpt", false, "VPN_PROTECTS_SATUS_PORMPT");
    }


    public VpnProtectStatusBeanDao(DaoConfig config) {
        super(config);
    }
    
    public VpnProtectStatusBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VPN_PROTECT_STATUS_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VPN_PROTECTS_SATUS\" INTEGER NOT NULL ," + // 1: vpnProtectsSatus
                "\"VPN_PROTECTS_SATUS_PORMPT\" TEXT);"); // 2: vpnProtectsSatusPormpt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VPN_PROTECT_STATUS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VpnProtectStatusBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getVpnProtectsSatus());
 
        String vpnProtectsSatusPormpt = entity.getVpnProtectsSatusPormpt();
        if (vpnProtectsSatusPormpt != null) {
            stmt.bindString(3, vpnProtectsSatusPormpt);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VpnProtectStatusBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getVpnProtectsSatus());
 
        String vpnProtectsSatusPormpt = entity.getVpnProtectsSatusPormpt();
        if (vpnProtectsSatusPormpt != null) {
            stmt.bindString(3, vpnProtectsSatusPormpt);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VpnProtectStatusBean readEntity(Cursor cursor, int offset) {
        VpnProtectStatusBean entity = new VpnProtectStatusBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // vpnProtectsSatus
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // vpnProtectsSatusPormpt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VpnProtectStatusBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVpnProtectsSatus(cursor.getInt(offset + 1));
        entity.setVpnProtectsSatusPormpt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VpnProtectStatusBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VpnProtectStatusBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VpnProtectStatusBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
